"use client";
import ThemeProvider from "@/providers/ThemeProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Montserrat, Roboto } from "next/font/google";
import { CssBaseline } from "@mui/material";
import "react-alice-carousel/lib/alice-carousel.css";
import CryptoProvider from "@/context/CryptoContext";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "800"],
  variable: "--montserrat",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--roboto",
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider>
      <CryptoProvider>
        <CssBaseline enableColorScheme />
        <html lang="en">
          <body className={`${montserrat.variable} ${roboto.variable}`}>
            {children}{" "}
          </body>
        </html>
      </CryptoProvider>
    </ThemeProvider>
  );
}
